# This is a mods.toml file for Forge 1.20.1.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${loader_version_range}" #mandatory

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="${mod_license}"

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="${mod_id}" #mandatory

# The version number of the mod
version="${mod_version}" #mandatory

# A display name for the mod
displayName="${mod_name}" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png" #optional

# A text field displayed in the mod UI
credits="ProtoManly (original author), Spud, Understimulate" #optional

# A text field displayed in the mod UI
authors="${mod_authors}" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''${mod_description}'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
config="atmospherica.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${mod_id}]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be valid
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="${forge_version_range}" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"

# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# Optional compatibility with Oculus (Iris shader mod for Forge)
[[dependencies.${mod_id}]]
    modId="oculus"
    mandatory=false
    versionRange="[1.6.0,)"
    ordering="AFTER"
    side="CLIENT"

# Optional compatibility with Embeddium (Sodium for Forge)
[[dependencies.${mod_id}]]
    modId="embeddium"
    mandatory=false
    versionRange="[0.2.0,)"
    ordering="AFTER"
    side="CLIENT"

# Optional compatibility with Rubidium (older Sodium fork for Forge)
[[dependencies.${mod_id}]]
    modId="rubidium"
    mandatory=false
    versionRange="[0.5.0,)"
    ordering="AFTER"
    side="CLIENT"

# Features are specific properties of the game environment, that you may want to declare you require.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
